# Generated by Django 4.0.6 on 2022-07-16 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_image', models.ImageField(blank=True, default='item.png', null=True, upload_to='item_image')),
                ('item_name', models.CharField(max_length=200)),
                ('item_detail', models.TextField()),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField()),
                ('startprice', models.IntegerField()),
                ('bidprice', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
