# Generated by Django 4.0.6 on 2022-07-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bidprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
