# Generated by Django 4.0.6 on 2022-07-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0002_alter_auction_bidprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
