# Generated by Django 4.0.6 on 2022-07-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
    ]
