# Generated by Django 4.0.6 on 2022-07-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0008_rename_user_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='bidprice',
        ),
        migrations.AddField(
            model_name='auction',
            name='highbid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='user_name',
            field=models.ManyToManyField(to='Auction.profile'),
        ),
    ]
