# Generated by Django 4.0.6 on 2022-07-16 10:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0009_remove_auction_bidprice_auction_highbid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auction.auction'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
