# Generated by Django 4.0.6 on 2022-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0010_remove_auction_user_name_profile_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
