# Generated by Django 4.0.6 on 2022-07-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0013_remove_profile_auction_auction_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='users',
        ),
        migrations.AddField(
            model_name='profile',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Auction.auction'),
        ),
    ]
