# Generated by Django 4.0.6 on 2022-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0014_remove_auction_users_profile_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='auction',
        ),
        migrations.AddField(
            model_name='profile',
            name='auction',
            field=models.ManyToManyField(blank=True, null=True, to='Auction.auction'),
        ),
    ]
